name: rfilesaver
description: "A Flutter Plugin to save file in android or ios device"
version: 0.0.4
homepage: https://github.com/code5061/rfilesaver.git
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jar5061.rfilesaver
        pluginClass: RfilesaverPlugin
      ios:
        pluginClass: RfilesaverPlugin
